language: csharp
solution: DnDTracker.sln
mono: none
dotnet: 2.2.401
jobs:
  include:
    - stage: build
      script: dotnet build -c Release
    - stage: test
      script: dotnet test ./src/DnDTracker.Tests/DnDTracker.Tests.csproj
    - stage: deploy
      script:
        - dotnet publish -o dndtracker-app
        - cd dndtracker-app
        - zip ../dndtracker-app.zip *
        - cd ..
        - zip deploy.zip ./dndtracker-app/dndtracker-app.zip aws-windows-deployment-manifest.json
        - aws eb deploy dndtracker-$ENVIRONMENT
stages:
  - build
  - test
  - name: deploy
    if: branch = master OR branch = develop
after_failure:
  - sleep 10