language: csharp
solution: DnDTracker.sln
mono: none
dotnet: 2.2.401
jobs:
  include:
    - stage: build
      script: dotnet build -c Release
    - stage: test
      script: dotnet test ./src/DnDTracker.Tests/DnDTracker.Tests.csproj
stages:
  - build
  - test
deploy:
  - provider: elasticbeanstalk
    access_key_id: $ACCESS_KEY
    secret_access_key: $SECRET_KEY
    region: us-east-2
    app: dndtracker-app
    env: dndtracker-$ENVIRONMENT
    bucket_name: dndtracker-$ENVIRONMENT
    zip_file: deploy.zip
    skip_cleanup: true
    on:
      branch: develop
  - provider: elasticbeanstalk
    access_key_id: $ACCESS_KEY
    secret_access_key: $SECRET_KEY
    region: us-east-2
    app: dndtracker-app
    env: dndtracker-$ENVIRONMENT
    bucket_name: dndtracker-$ENVIRONMENT
    zip_file: deploy.zip
    skip_cleanup: true
    on:
      branch: master
after_failure:
  - sleep 10