language: csharp
solution: dndtracker.sln
mono: none
dotnet: 2.2.401
jobs:
  include:
    - stage: build
      script: dotnet build ./src/DnDTracker.sln -c Release
    - stage: test
      script: dotnet test ./src/DnDTracker.Tests/DnDTracker.Tests.csproj
#    - stage: deploy
#      script: ls
stages:
  - build
  - test
#  - deploy