language: csharp
solution: dndtracker.sln
mono: none
dotnet: 2.2.401
jobs:
  include:
    - stage: build
      script: dotnet restore
    - stage: test
      script: dotnet test
#    - stage: deploy
#      script: ls
stages:
  - build
  - test
#  - deploy